Parameters:
  NameOfService:
    Description: "Name of Service"
    Type: String

  InstanceTypeParameter:
    Description: "Enter Instance type (t2.micro, t2.small, or t2.medium)"
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  KeyName:
    Description: "Name of EC2 instance login key"
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  AmiRegionMap:
    us-east-1:
      AMI: ami-02c21308fed24a8ab
    us-east-2:
      AMI: ami-085f9c64a9b75eed5

Resources:
  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH and HTTP access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 49.206.39.12/32

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref KeyName
      ImageId: !FindInMap
        - AmiRegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: "Name"
          Value: !Ref NameOfService
      SecurityGroups:
        - !Ref VprofileSG
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash -xe
            yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource MyInstance --region ${AWS::Region}
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource MyInstance --region ${AWS::Region}
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              php: []
              httpd: []
              wget: []
              unzip: []
              git: []
          commands:
            test:
              command: "wget https://www.tooplate.com/zip-templates/2135_mini_finance.zip && unzip 2135_mini_finance.zip && cp -r 2135_mini_finance/* /var/www/html "
          files:
            /var/www/html/hello.html:
              content: !Sub |
                <!Doctype html>
                <html>
                <body>
                <h1>Welcome to CloudFormation</h1>
                <p>This site is deployed by CloudFormation</p>
                </body>
                </html>
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true

Outputs:
  PrintDns:
    Value: !GetAtt
      - MyInstance
      - PublicDnsName
